#!/usr/bin/env bash

CONFIG_FILE="$XDG_CONFIG_HOME/term_theme_switcher/config"

# Check if the config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file $CONFIG_FILE does not exist"
    exit 1
fi

# get all themes from config file
source $CONFIG_FILE

# get the index of the chosen theme
get_theme_idx() {
    local theme="$1"
    index=-1
    for i in "${!names[@]}"; do
        if [[ "${names[$i]}" == "$theme" ]]; then
            index=$i
            break
        fi
    done
    echo "$index"
}

# sets the themes in the ~/.theme file
set_theme() {
    local idx="$1"
    local theme_file="$HOME/.theme"

    if [ ! -f "$theme_file" ]; then
        touch $theme_file
    fi

    if [ ! -w "$theme_file" ]; then
        echo "Error: Theme file $theme_file is not writable"
        return 1
    fi

    # remove theme_file contents
    : >$theme_file

    echo "Updated ~/.theme:"
    for program in "${programs[@]}"; do
        eval "theme=(\"\${${program}[$idx]}\")"

        echo "$program=\"$theme\"" >>"$theme_file"

        echo "$program=\"$theme\""
    done
    return 0
}

# make a \n seperated string of theme names
themes_string=$(printf "%s\n" "${names[@]}")

# make user choose a theme using fzf
chosen=$(echo "$themes_string" | fzf)
# if user exited without changing do nothing
if [ "$chosen" = "" ]; then
    exit 0
fi

idx=$(get_theme_idx "$chosen")
# set theme in the ~/.theme file
set_theme "$idx"
